In [3]:
import pandas as pd

# Beolvasás index nélkül
df = pd.read_csv("../data/processed/stock_data.csv", index_col=None)

df

,Date,Close,High,Low,Open,Volume
0,NaN,AAPL,AAPL,AAPL,AAPL,AAPL
1,2025-04-28,209.8647918701172,211.2230113707532,207.1883090170199,209.72497582911666,38743100
2,2025-04-29,210.9333953857422,211.96204522644123,208.09710321217068,208.41669143858087,36827600
3,2025-04-30,212.22171020507812,213.30029766677714,206.399343338795,209.02590396975114,52286500
4,2025-05-01,213.04063415527344,214.2790004444518,208.62640936955898,208.80618155790114,57365700
5,2025-05-02,205.08106994628906,206.71892151455646,201.89524528415058,205.82009105417706,101010600
6,2025-05-05,198.62953186035156,203.83271551835597,197.9504297070337,202.83402512431957,69018500
7,2025-05-06,198.25001525878906,200.38721199140494,196.7619763948813,197.9504203457911,51216500
8,2025-05-07,195.99298095703125,199.1788056079939,192.99690991055434,198.90915494694545,68536700
9,2025-05-08,197.2313690185547,199.78801395815432,194.42503624466005,197.46106353953903,50478900
10,2025-05-09,198.27000427246094,200.2773664943336,197.28129528859796,198.739389980464,36453900
11,2025-05-12,210.7899932861328,211.27000427246094,206.75,210.97000122070312,63775800
12,2025-05-13,212.92999267578125,213.39999389648438,209.0,210.42999267578125,51909300
13,2025-05-14,212.3300018310547,213.94000244140625,210.5800018310547,212.42999267578125,49325800
14,2025-05-15,211.4499969482422,212.9600067138672,209.5399932861328,210.9499969482422,45029500
15,2025-05-16,211.25999450683594,212.57000732421875,209.77000427246094,212.36000061035156,54737900
16,2025-05-19,208.77999877929688,209.47999572753906,204.25999450683594,207.91000366210938,46140500
17,2025-05-20,206.86000061035156,208.47000122070312,205.02999877929688,207.6699981689453,42496600
18,2025-05-21,202.08999633789062,207.0399932861328,200.7100067138672,205.1699981689453,59211800
19,2025-05-22,201.36000061035156,202.75,199.6999969482422,200.7100067138672,46742400
20,2025-05-23,195.27000427246094,197.6999969482422,193.4600067138672,193.6699981689453,78314800
21,2025-05-27,198.61000061035156,199.1699981689453,197.42999267578125,198.3000030517578,12102187